apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: <NAMESPACE>
spec:
  type: LoadBalancer
  selector:
    app: example
  ports:
    - name: example-port
      protocol: TCP
      port: 8080
      targetPort: 8080
